### ISSUE TITLE
How to hook request to this new API?

### ISSUE THREAD

**Issue by lupohan44** [Titoot/httptoolkit-interceptor#1]
Hi, thank you for your project. Could you please share how to hook original request to this new API?

**Comment by Titoot** [comment]
Hey, wasn't expecting anyone to find it this soon, So I didn't write it because I did it manually. 
Either way since it's an electron app so you can unpack the `app.asar` file using `asar`

Which can be installed using npm
```
npm install -g asar

```
And then extract using
```
asar extract app.asar app
```

then replace the httptoolkit domain with the new API

And you might need to disable CORS in the server file if I remember correctly
And you disable it by adding localhost to allowed origins

When I'm on the pc I'll provide further instructions and I'll update the code to make it more automatic

**Comment by lupohan44** [comment]
Thank you so much

**Comment by Titoot** [comment]
I finished most of the automatic patching, when I'm done I'll push it and close the issue

**Comment by Titoot** [comment]
I committed the changes, which now include automatic CORS and Asar file patching. So I guess now the issue can be closed
